---

- name: Basic configuration
  template: src=nrpe/nrpe.cfg.j2 dest=/etc/nrpe.cfg
  notify: restart nrpe

- name: Create /etc/nrpe.d
  file: path=/etc/nrpe.d state=directory

- name: System checks configuration
  template: src=nrpe/system.cfg.j2 dest=/etc/nrpe.d/system.cfg
  notify: restart nrpe
