---

# Get cluster name
- name: Get cluster name
  shell: awk '/cluster_name/ {print $2}' /etc/corosync/corosync.conf
  register: crm_cluster_name
  run_once: true



- name: Corosync configuration
  template: src=corosync.conf.j2 dest=/etc/corosync/corosync.conf
  register: corosync_template_result
  vars:
    generated_cluster_port: 'ansible_{{ net_cluster_port }}'
    cluster_name: crm_cluster_name.stdout

- name: Restart corosync
  shell: "{{ item }}"
  with_items:
    - crm cluster stop
    - crm cluster start
  when:
    - corosync_template_result|changed
