---

- name: LV create "{{ item.vg }}/{{ item.lv }}"
  lvol: vg={{ item.vg }} lv={{ item.lv }} size={{ item.size }}
  when:
    - item.fstype != "tmpfs"
  run_once: true

- name: LV mkfs "{{ item.vg }}/{{ item.lv }}"
  filesystem: fstype={{ item.fstype }} dev=/dev/{{ item.vg }}/{{ item.lv }}
  when:
    - item.fstype != "tmpfs"

# Pacemaker configuration to mount the LV
- name: Check if the LV primitive is present
  shell: crm configure show
  register: crm_conf
  run_once: true
  when:
    - is_pacemaker_running.stdout.find("true") > -1

- name: Create primitive "{{ item.vg }}_{{ item.lv }}"
  shell: >
    crm configure primitive "{{ item.vg }}_{{ item.lv }}" Filesystem \
        directory="{{ item.mountpoint }}" \
        param device="/dev/{{ item.vg }}/{{ item.lv }}" \
        fstype="{{ item.fstype }}" \
        op monitor timeout=40 interval=20 \
        op start timeout=60 interval=0 \
        op stop timeout=60 interval=0 \
        meta target-role=Stopped
  run_once: true
  when:
    - crm_conf.stdout.find("primitive {{ item.vg }}_{{ item.lv }}") < 0
    - is_pacemaker_running.stdout.find("true") > -1

- name: Check group configuration "{{ item.vg }}_rg"
  shell: crm configure show {{ item.vg }}_rg
  register: crm_group_conf
  when:
    - is_pacemaker_running.stdout.find("true") > -1

- name: Add the LV primitive "{{ item.lv }}" to the group
  shell: crm -w configure modgroup "{{ item.vg }}_rg" add "{{ item.vg }}_{{ item.lv }}"
  run_once: true
  when:
    - crm_group_conf.stdout.find("{{ item.lv }}") < 0
    - is_pacemaker_running.stdout.find("true") > -1

- name: Start the primitive "{{ item.vg }}_{{ item.lv }}"
  shell: crm -w resource start {{ item.vg }}_{{ item.lv }}
  when:
    - is_pacemaker_running.stdout.find("true") > -1

# Configuration without pacemaker: fstab and mount
- name: Update the fstab and mount "{{ item.vg }}/{{ item.lv }}"
  mount: path="{{ item.mountpoint }}" src="/dev/{{ item.vg }}/{{ item.lv }}" fstype="{{ item.fstype }}" boot=true state=present
  when:
    - is_pacemaker_running.stdout.find("false") > -1
