---

- name: Does the LUN exist?
  stat: path={{ application.storage.lun }}
  register: lun_check

- name: Rescan SCSI
  shell: /usr/bin/rescan-scsi-bus.sh
  when: lun_check.stat.exists == false

- name: Does the LUN exist?
  stat: path={{ application.storage.lun }}
  register: lun_check

- fail: msg="Stop if no LUN"
  when:
   - lun_check.stat.exists == false

- name: VG Create
  lvg: vg={{ application.name }} pvs={{ application.storage.lun }} vg_options="-cn"

- name: Create root path
  file: path=/srv/cluster/{{ application.name }} state=directory owner=root group=root

