---

# Create the volume group
- include: disk.yml

# Create the logical volumes
- include: volumes/main.yml

# LXD profile:
# - Set the network configuration
# http://docs.ansible.com/ansible/latest/lxd_profile_module.html
- name: Create a profile
  lxd_profile:
    name: lxc_local
    state: present
    config: {}
    description: One-node profile
    devices:
      eth0:
        nictype: macvlan
        parent: br0
        type: nic

# Start the containe
- name: Start the container
  lxd_container:
    name: {{ application.name }}
    state: started
    source:
      type: image
      mode: pull
      server: https://images.linuxcontainers.org
      protocol: lxd
      alias: ubuntu/xenial/amd64
    profiles: ["lxc_local"]
    wait_for_ipv4_addresses: true
    timeout: 600

# Attach storage
- name: Attach storage
  shell: lxc storage volume attach <pool-name> <volume-name> <container-name> <device-name> path=</some/path/in/the/container>
