---

# We need to know how to manage the VG. If pacemaker is running, the resources are created
- name: Check if pacemaker is running
  shell: systemctl is-running pacemaker.service
  register: is_pacemaker_running

- name: vgscan
  shell: vgscan
  register: vgscan_status

# Libvirt stuff
- include: libvirt.yml
  when: hosting_use_libvirt_lxc == true

- include: lxd.yml
  when: hosting_use_lxd == true
