---

# We need to know how to manage the VG. If pacemaker is running, the resources are created
- name: Check if pacemaker is running
  shell: systemctl is-running pacemaker.service
  register: is_pacemaker_running

- name: vgscan
  shell: vgscan
  register: vgscan_status

# Create the volume group
- include: disk.yml

# Create the logical volumes
- include: volumes/main.yml

- name: Check libvirt networking
  shell: virsh -c lxc:/// net-list
  register: libvirt_net_list

- include: network.yml
  with_items: application.ips

# Libvirt stuff
- include: libvirt.yml
