---

- fail: msg="libvirt_net_list is not defined"
  when: libvirt_net_list is not defined

- name: Network configuration for libvirt
  template: src=../templates/network.xml.j2 dest=/tmp/{{ item.vlan }}.network.xml
  when: libvirt_net_list.stdout.find("ovs-network-{{ item.vlan }}") < 0

# libvirt ansible modules exists but have not been tested yet
- name: Network creation for libvirt
  shell: >
    virsh -c lxc:/// net-define /tmp/{{ item.vlan }}.network.xml ;
    virsh -c lxc:/// net-autostart ovs-network-{{ item.vlan }} ;
    virsh -c lxc:/// net-start ovs-network-{{ item.vlan }}
  when: libvirt_net_list.stdout.find("ovs-network-{{ item.vlan }}") < 0

- name: XML files cleanup
  shell: rm -f /tmp/{{ item.vlan }}.network.xml
  when: libvirt_net_list.stdout.find("ovs-network-{{ item.vlan }}") < 0
