---

- name: Local building
  delegate_to: localhost
  become: no
  run_once: true
  when:
    - install_openstack_fencing_from_github == true
    - build_openstack_fencing_from_deployment_host == true
  block:
    - name: Clone the repo
      git:
        repo: https://github.com/ClusterLabs/fence-agents
        dest: "{{ cluster_stonith_openstack_fencing_repo_path }}"

    - name: Set the python interpretor
      lineinfile:
        path: "{{ cluster_stonith_openstack_fencing_repo_path }}/agents/openstack/fence_openstack.py"
        regexp: "^#!"
        line: "#! {{ cluster_usr_prefix }}/bin/python3"

#    - name: Install the agent
#      copy: src="{{ item.src }}" dest="{{ item.dest }}" mode="{{ item.mode }}"
#      with_items:
#        - src: "{{ cluster_stonith_openstack_fencing_repo_path }}/agents/openstack/fence_openstack.py"
#          dest: "{{ cluster_usr_prefix }}/sbin/fence_openstack"
#          mode: "0755"

- name: Remote building
  become: no
  when:
    - install_openstack_fencing_from_github == true
    - build_openstack_fencing_from_deployment_host == false
  block:
    - name: Clone the repo
      git:
        repo: https://github.com/ClusterLabs/fence-agents
        dest: "{{ cluster_stonith_openstack_fencing_repo_path }}"
        force: yes
        version: master

    - name: Set the python interpretor
      lineinfile:
        path: "{{ cluster_stonith_openstack_fencing_repo_path }}/agents/openstack/fence_openstack.py"
        regexp: "^#!"
        line: "#! {{ cluster_usr_prefix }}/bin/python3"
