---

- name: Install HA pattern (SLES only)
  zypper: type=pattern name={{ item }} state=present
  with_items:
    - ha_sles
  when: ansible_distribution == 'SLES'

- name: Install corosync / pacemaker packages
  package:
    name: "{{ cluster_distro_packages }}"
    state: "{{ cluster_package_state }}"
    update_cache: "{{ (ansible_pkg_mgr == 'apt') | ternary('yes', omit) }}"
    cache_valid_time: "{{ (ansible_pkg_mgr == 'apt') | ternary(cache_timeout, omit) }}"
  register: install_packages
  until: install_packages is success
  retries: 5
  delay: 2
  tags:
    - install-apt
    - install-yum
    - install-zypper

- name: Install sbd package
  package:
    name: sbd
    state: "{{ cluster_package_state }}"
    update_cache: "{{ (ansible_pkg_mgr == 'apt') | ternary('yes', omit) }}"
    cache_valid_time: "{{ (ansible_pkg_mgr == 'apt') | ternary(cache_timeout, omit) }}"
  when:
    - cluster_stonith_use_sbd == true
    - ansible_virtualization_type != 'lxc'
    - ansible_distribution != 'SLES' # included in the ha_sles pattern

- name: Install python-parallax using pip (Debian / Ubuntu / FreeBSD)
  pip: name=parallax extra_args={{ pip_extra_args }}
  when:
      - ansible_os_family | lower == 'debian' or ansible_os_family | lower == 'freebsd'
      - ansible_os_family | lower != 'ubuntu' and ansible_distribution_major_version | lower | int < 18
