---

- name: Create /etc/pacemaker
  file: path=/etc/pacemaker state=directory

- name: Set monitoring probes (nrpe)
  template: src=cluster.cfg.j2 dest=/etc/nrpe.d/cluster.cfg
  notify: restart nrpe
  when: cluster_monitoring_use_nrpe == true

- name: Set monitoring probes (consul)
  template: src=consul/cluster.json.j2 dest=/etc/consul.d/cluster.json
  notify: reload consul
  when: cluster_monitoring_use_consul == true

