---

- name: Local cleaning
  delegate_to: localhost
  become: no
  run_once: true
  when:
    - install_openstack_fencing_from_github | lower == 'true'
    - build_openstack_fencing_from_deployment_host | lower == 'true'
  block:
    - name: Cleanup
      file:
        path: "{{ cluster_stonith_openstack_fencing_repo_path }}"
        state: absent

- name: Remote cleaning
  when:
    - install_openstack_fencing_from_github | lower == 'true'
    - build_openstack_fencing_from_deployment_host | lower == 'false'
  block:
    - name: Cleanup
      file:
        path: "{{ cluster_stonith_openstack_fencing_repo_path }}"
        state: absent
