---

- name: Post-Install | monitoring | Create /etc/pacemaker
  file: path=/etc/pacemaker state=directory

- name: Post-Install | monitoring | Set monitoring probes (nrpe)
  template: src=cluster.cfg.j2 dest=/etc/nrpe.d/cluster.cfg
  notify: restart nrpe
  when: cluster_monitoring_use_nrpe | lower == 'true'

- name: Post-Install | monitoring | Set monitoring probes (consul)
  template: src=consul/service.json.j2 dest=/etc/consul.d/{{ item.service.name }}.json
  with_items: "{{ cluster_monitoring_consul }}"
  notify: reload consul
  when: cluster_monitoring_use_consul | lower == 'true'

