---

- name: Check cluster status
  shell: crm configure show || true
  register: crm_configure_show
  run_once: true

- name: Disable sbd on containers
  service: name=sbd enabled=false state=stopped
  when: ansible_virtualization_type == 'lxc' # Containers do not see physical block devices

- name: LUNs initialisation for SBD if the resource does not exist
  shell: sbd -d {{ item }} create
  with_items: "{{ cluster_stonith_sbd_luns }}"
  when:
    - crm_configure_show.stdout.find("sbd") < 0
    - ansible_virtualization_type != 'lxc' # Physical nodes or Xen/KVM
  run_once: true

- name: Configure sbd if the resource does not exist
  replace: dest={{ cluster_sbd_configuration }} regexp='^SBD_DEVICE=(.*?)$' replace='SBD_DEVICE="{{ cluster_stonith_sbd_luns | join(';') }}"'
  when:
    - crm_resources_stonith.stdout.find("sbd") < 0
    - cluster_stonith_sbd_luns | length > 0
    - ansible_virtualization_type != 'lxc' # Physical nodes or Xen/KVM
  notify: restart sbd resource

- name: Disable sbd pacemaker integration on two-nodes clusters when three sbd devices are given
  replace: dest={{ cluster_sbd_configuration }} regexp='^SBD_PACEMAKER=(.*?)$' replace='SBD_PACEMAKER="no"'
  when:
    - cluster_expected_votes == 2
    - cluster_stonith_sbd_luns | length == 3

- name: sbd on boot on compute nodes
  service: name=sbd enabled=yes
  when:
    - ansible_virtualization_type != 'lxc' # Physical nodes or Xen/KVM

# TODO: prevent node from joining the cluster if fenced

# Create SBD resource
- name: Create SBD resource
  shell: crm -w script run sbd id=stonith_sbd
  run_once: true
  when: cluster_stonith_use_sbd == true
