- name: Set monitoring probes (nrpe)
  template: src=cluster.cfg.j2 dest=/etc/nrpe.d/cluster.cfg
  notify: restart nrpe
  when: monitoring_use_nrpe | lower == 'true'

- name: Set monitoring probes (consul)
  template: src=consul/cluster.json.j2 dest=/etc/consul.d/cluster.json
  notify: reload consul
  when: monitoring_use_consul | lower == 'true'
