---

# Check if we use FQDNs
- name: Get node's name
  command: crm_node -n
  register: crm_node_name

# Utilization attributes
- name: Define cpu and memory allocation ratio
  shell: crm_attribute -z --node {{ crm_node_name.stdout }} --name {{ item.property }} --update {{ item.value }}
  with_items:
    - property: cpu
      value: "{{ (ansible_processor_vcpus * cluster_allocation_vcpus_ratio) | int }}"
    - property: hv_memory
      value: "{{ (ansible_memtotal_mb * 1024 * cluster_allocation_memory_ratio) | int }}"
  when: ansible_virtualization_role == 'host'

# Usage attributes
- name: Add {{ cluster_node_attribute_key }} attribute
  command: crm_attribute --node {{ crm_node_name.stdout }} --name {{ cluster_node_attribute_key }} --update {{ cluster_node_attribute_value }}
  when:
    - cluster_node_attribute_key|length > 0
    - cluster_node_attribute_value|length > 0
