---

- name: restart sssd
  shell: virsh -c lxc:/// lxc-enter-namespace --noseclabel {{ application.name }} -- /usr/bin/systemctl restart sssd

- name: restart sshd
  shell: virsh -c lxc:/// lxc-enter-namespace --noseclabel {{ application.name }} -- /usr/bin/systemctl restart sshd

- name: restart firewall
  shell: virsh -c lxc:/// lxc-enter-namespace --noseclabel {{ application.name }} -- /usr/bin/systemctl restart SuSEfirewall2

- name: reload interfaces
  shell: virsh -c lxc:/// lxc-enter-namespace --noseclabel {{ application.name }} -- for nic in $(wicked show all|awk '/^\w/ {print $1}') ; do wicked ifreload $nic ; done
  notify: start interface public
