---

- name: Create the bond
  shell: yast lan add name={{ item.bond }} slaves="{{ item.ethernet_ports }}" bootproto=NONE
  when: item.ethernet_ports.find(" ") > -1

- name: Create the bridge
  shell: yast lan add name={{ item.bridge }} bridge_ports={{ item.bond }} bootproto=NONE
  when: item.ethernet_ports.find(" ") > -1

- name: Create the bridge
  shell: yast lan add name={{ item.bridge }} bridge_ports={{ item.ethernet_ports }} bootproto=NONE
  when: item.ethernet_ports.find(" ") < 0
