---

- name: Install telegraf
  apt: name={{ item }} state=latest
  with_items:
    - telegraf
  when: use_metrics_telegraf == true

- name: Install collect
  apt: name={{ item }} state=latest
  with_items:
    - collectd
  when: use_metrics_collectd == true
