---

- name: Create the local volume group
  lvg: vg={{ lxd_default_storage_pool.name }} pvs={{ lxd_default_storage_pool.source }} vg_options="-cn"

- name: Create the thin logical volume
  lvol: vg={{ lxd_default_storage_pool.name }} lv=LXDThinpool size="50%VG" opts="--thin"

- name: Create the default storage pool
  shell: >
    lxc storage list | grep {{ lxd_default_storage_pool.name }} || \
    lxc storage create {{ lxd_default_storage_pool.name }} \
      {{ lxd_default_storage_pool.driver }} \
      source={{ lxd_default_storage_pool.source }}
#      description="Default storage pool for clustered containers"
