# Ansible modules for openvswitch are in preview state.

- name: Start OpenVSwitch
  service: name=openvswitch.service state=started enabled=true

# VLAN tagging

- name: Front Office Networking - VLAN tagging
  shell: ovs-vsctl set port {{ net_front_port }} trunks="{{ net_front_vlans }}"
  when:
    - net_front_vlans != 'None'

- name: Back Office Networking - VLAN tagging
  shell: ovs-vsctl set port {{ net_back_port }} trunks="{{ net_back_vlans }}"
  when:
    - net_back_vlans != 'None'

- name: Admin Networking - VLAN tagging
  shell: ovs-vsctl set port {{ net_admin_port }} trunks="{{ net_admin_vlans }}"
  when:
    - net_admin_vlans != 'None'

- name: Cluster Networking - VLAN tagging
  shell: ovs-vsctl set port {{ net_cluster_port }} trunks="{{ net_cluster_vlans }}"
  when:
    - net_cluster_vlan != 'None'

# Interfaces creation

- name: Cluster Networking - Port creation with tag
  shell: ovs-vsctl --may-exist add-port ovs-back {{ net_cluster_port }} -- set interface {{ net_cluster_port }} type=internal
  when:
    - net_cluster_vlan != 'None'

- name: Cluster Networking - Port creation without tag
  shell: ovs-vsctl --may-exist add-port ovs-back {{ net_cluster_port }} tag={{ net_cluster_vlan }} -- set interface {{ net_cluster_port }} type=internal
  when:
    - net_cluster_vlan != 'None'
