---

- name: Creation de la ressource conteneur
  shell: >
    crm configure primitive "{{ application.name }}_lxc" VirtualDomain \
      config="/etc/pacemaker/{{ application.name }}.xml" \
      hypervisor='lxc:///' \
      autoset_utilization_cpu=true \
      autoset_utilization_hv_memory=true \
      save_config_on_stop=false \
      sync_config_on_stop=false \
      monitor_scripts=/opt/monitor_lxc.sh \
      force_stop="true" \
      meta target-role=Stopped
  when: crm_conf.stdout.find("primitive {{ application.name}}_lxc VirtualDomain") < 0
  run_once: true

- name: Mise en groupe du conteneur {{ application.name }}_lxc
  shell: crm configure modgroup "{{ application.name }}_rg" add "{{ application.name}}_lxc"
  when: crm_group_conf.stdout.find("{{ application.name }}_lxc") < 0
  run_once: true

- name: Lancement de la ressource {{ application.name }}_lxc
  shell: crm -w resource start "{{ application.name }}_lxc"
  run_once: true

- name: Attente de la disponibilite du conteneur
  shell: crm resource status {{ application.name }}_lxc
  register: crm_resource_show
  until: crm_resource_show.stdout.find("{{ application.name }}_lxc is running") > -1
  retries: 10
  delay: 2
  run_once: true
