---

# We need to know how to manage the VG. If pacemaker is running, the resources are created
- name: Check if pacemaker is running
  shell: systemctl is-running pacemaker.service
  register: is_pacemaker_running

- fail: msg="pacemaker must be running"
  when: is_pacemaker_running.stdout.find("inactive") > -1

- name: vgscan
  shell: vgscan
  register: vgscan_status

# Create the volume group
- include: disk.yml

- name: Find which node hosts the VG
  shell: crm_resource --locate --resource "{{ application.name }}_vg"
  register: crm_resource_locate_vg

# Create the logical volumes
- include: volumes/main.yml
  when: crm_resource_locate_vg.stdout.find("{{ ansible_hostname }}") > -1

- name: Check libvirt networking
  shell: virsh -c lxc:/// net-list
  register: libvirt_net_list

- include: network.yml
  with_items: application.ips

# Libvirt stuff
- include: libvirt.yml
