---
# handlers file for ansible-ha-cluster

- name: reload consul
  shell: >
    systemctl is-active consul && {{ consul_bin }} reload \
    || systemctl start consul

- name: restart hawk resource
  shell: crm -w resource restart hawk

- name: restart nrpe
  service: name=nrpe state=restarted enabled=yes

- name: restart sbd resource
  shell: crm -w resource restart sbd

- name: reload firewalld
  command: firewall-cmd --reload
