---
# handlers file for ansible-ha-cluster

- name: reload consul
  shell: "{{ consul_bin }} reload"
  when: consul_service.stdout.find('ko') < 0

- name: restart hawk resource
  shell: crm -w resource restart hawk

- name: restart nrpe
  service: name=nrpe state=restarted enabled=yes

- name: restart sbd resource
  shell: crm -w resource restart sbd

- name: reload firewalld
  command: firewall-cmd --reload
