# handlers file for ansible-ha-cluster

- name: reload consul
  service: name=consul state=reloaded

- name: restart hawk resource
  command: crm -w resource restart hawk

- name: restart nrpe
  service: name=nrpe state=restarted enabled=yes

- name: restart sbd resource
  command: crm -w resource restart sbd

- name: reload firewalld
  command: firewall-cmd --reload
