---

- name: Check du fonctionnement du service de cluster
  shell: systemctl is-active pacemaker || true
  register: pcmk_status
  tags:
    - always

- include: packaging.yml
  tag:
    - packaging

- include: monitoring.yml
  tags:
    - monitoring

- include: metrics.yml
  tags:
    - metrics

- include: network.yml
  tags:
    - network
