---

- include: options_check.yml
  run_once: true
  tags:
    - always
    - system_check

- name: Check pacemaker state
  shell: systemctl is-active pacemaker && echo active || echo ko
  register: pcmk_status
  when: ansible_system == 'Linux'
  tags:
    - always

- name: Check pacemaker state
  shell: service pacemaker status && echo active || echo ko
  register: pcmk_status
  when: ansible_system == 'FreeBSD'
  tags:
    - always

- include: packaging.yml
  tag:
    - system_packaging

- include: monitoring.yml
  tags:
    - system_monitoring

- include: metrics.yml
  tags:
    - system_metrics

- include: network.yml
  tags:
    - system_network

- include: storage/lxd_local.yml
  when: hosting_use_lxd == true
  tags:
    - system_storage
