---

- include: options_check.yml
  run_once: true
  tags:
    - always
    - system_check

- name: Check pacemaker state
  shell: systemctl is-active pacemaker || true
  register: pcmk_status
  tags:
    - always

- include: packaging.yml
  tag:
    - system_packaging

- include: monitoring.yml
  tags:
    - system_monitoring

- include: metrics.yml
  tags:
    - system_metrics

- include: network.yml
  tags:
    - system_network
