---

- include: network/ovs.yml
  when:
    - net_use_openvswitch == true
    - cluster_role == 'compute'

- include: network/linux_bridge/suse.yml
  when:
    - ansible_os_family == 'Suse'
    - net_use_linux_bridge == true

- include: network/ports/suse.yml
  when:
    - ansible_os_family == 'Suse'
    - net_cluster.address != "None"

- include: network/ports/ubuntu.yml
  when:
    - ansible_distribution == 'Ubuntu'
    - net_cluster.address is defined

- include: network/linux_bridge/ubuntu.yml
  when:
    - ansible_distribution == 'Ubuntu'
    - net_use_linux_bridge == true
