---

- include: network/ovs.yml
  when:
    - net_use_openvswitch == true
    - cluster_role == 'compute'

- include: network/suse.yml
  when:
    - ansible_os_family == 'Suse'
    - net_cluster.address != "None"

- include: network/ubuntu.yml
  when:
    - ansible_os_family == 'Ubuntu'
    - net_cluster.address is defined
