---

- fail: msg='Only one monitoring method should be used'
  when:
   - monitoring_use_consul == true
   - monitoring_use_nrpe == true

- fail: msg='Only one metrics method should be used'
  when:
   - metrics_use_collectd == true
   - metrics_use_telegraf_== true

- fail: msg="Two is the minimum number of nodes"
  when:
    - cluster_expected_nodes < 2

- fail: msg="On a two-nodes cluster, a remote ping address must be given"
  when:
    - cluster_ping_remote_addr == 'None'
    - cluster_expected_nodes < 3

- fail: msg="The number of nodes in the group must equal the number of expected nodes"
  when:
    - play_hosts|length != cluster_expected_nodes

- fail: msg="You need to choose between libvirt/LXC and LXD"
  when:
    - hosting_use_libvirt_lxc == true and hosting_use_lxd == true or hosting_use_libvirt_lxc == false and hosting_use_lxd == false
    - ansible_system == 'Linux'

- fail: msg="LXD is only available on Ubuntu"
  when:
    - hosting_use_lxd == true
    - ansible_distribution != 'Ubuntu'

- fail: msg="A consul endpoint must be given to make agent join the cluster"
  when:
    - monitoring_use_consul == true
    - monitoring_consul_server_endpoint == 'None'
