---

- name: Install pacemaker / corosync packages
  pkgng: name={{ item }} state=present
  with_items:
    - crmsh
    - pacemaker
    - resource-agents
    - py27-pip
    - fping

- name: Hack for python-parallax (for crm script)
  pip: name=parallax

- name: Install packages for compute nodes (OpenVSwitch)
  pkgng: name={{ item }} state=present
  with_items:
    - openvswitch
  when:
    - cluster_role == 'compute'
    - net_use_openvswitch == true

- name: Install SBD
  pkgng: name=sbd state=present
  when:
    - cluster_role == 'compute'
    - ansible_virtualization_role == 'host'

# There resource-agents might be present in the official package
- name: Additional resource-agent
  copy: src={{ item }} dest=/usr/local/lib/ocf/resource.d/heartbeat/{{ item }} mode=0755 force=no
  with_items:
    - ovsmonitor
