---

# If we use SLES, a pattern is available to install a group of packages at once.
- name: Install HA pattern (SLES only)
  zypper: type=pattern name={{ item }} state=present
  with_items:
    - ha_sles
  when: ansible_distribution == 'SLES'

- name: Install pacemaker / corosync packages
  zypper: name={{ item }} state=present
  with_items:
    - pacemaker
    - crmsh
  when: ansible_distribution != 'SLES'

- name: Install packages for compute nodes (LXC, cLVM...)
  zypper: name={{ item }} state=present
  with_items:
    - fping
    - libvirt-daemon-lxc
    - libvirt-daemon
    - lvm2-clvm
    - lvm2-cmirrord
    - libdlm
  when:
    - cluster_role == 'compute'
    - hosting_use_libvirt_lxc == true

- name: Install packages for compute nodes (OpenVSwitch)
  zypper: name={{ item }} state=present
  with_items:
    - openvswitch
  when:
    - cluster_role == 'compute'
    - net_use_openvswitch == true

# TODO: use pip or local scripts instead of RPM packaging
#- name: Install utility and monitoring packages (metrics, scripts)
#  zypper: name={{ item }} state=latest
#  with_items:
#    - monitoring-plugins-crm
#    - cluster-utils

# There resource-agents might be present in the official package
- name: Additional resource-agent
  copy: src={{ item }} dest=/usr/lib/ocf/resource.d/heartbeat/{{ item }} mode=0755 force=no
  with_items:
    - ovsmonitor
    - MachineInfo
