    - name: Installation and setup of corosync / pacemaker
      hosts: compute-infra_hosts
      user: root
      roles:
        - { role: "ansible-ha-cluster" }
      vars:
        cluster_name: infra_hosts
        cluster_ring0_port: eth0
        cluster_ring1_port: eth1
        cluster_expected_votes: "{{ groups['compute-infra_hosts'] | length }}"
