---

- include: volume.yml
  with_items:
    - lv: sys
      vg: "{{ application.name }}"
      fstype: xfs
      mountpoint: "/"
      size: 5g
    - lv: log
      vg: "{{ application.name }}"
      fstype: xfs
      mountpoint: "/var/log"
      size: 1g
    - lv: home
      vg: "{{ application.name }}"
      fstype: xfs
      mountpoint: "/home"
      size: 1g

- include: volume.yml
  with_items:
    - lv: oracle
      vg: "{{ application.name }}"
      fstype: xfs
      mountpoint: "/opt/oracle"
      size: 7g
  when: application.type == "oracle"

- include: volume.yml
  with_items:
    - lv: pgsql
      vg: "{{ application.name }}"
      fstype: xfs
      mountpoint: "/var/lib/pgsql"
      size: 200m
  when: application.type == "postgres"

- include: volume.yml
  with_items:
    '{{application.storage.filesystems}}'
  when: application.storage.filesystems is defined

