---

- name: Create /etc/pacemaker
  file: path=/etc/pacemaker state=directory owner=hacluster
  when: ansible_system == 'Linux'

- name: Create /usr/local/etc/pacemaker
  file: path=/usr/local/etc/pacemaker state=directory owner=hacluster
  when: ansible_system == 'FreeBSD'

- name: Start apparmor
  service: name={{ item }} state=started enabled=yes
  with_items:
   - apparmor.service
  when: ansible_system == 'Linux'

# LXD does not need any monitoring script
- name: Monitoring script for LXC containers
  copy: src=monitor_lxc.sh dest=/opt/monitor_lxc.sh mode=0755
  when: ansible_os_family == 'Suse'

- name: Set SSL certs for Hawk
  copy: src={{ item }} dest=/etc/{{ item }} owner=root group=haclient mode=0640
  with_items:
    - "{{ cluster_hawk_file_key }}"
    - "{{ cluster_hawk_file_pem }}"
  notify: restart hawk
  when:
    - cluster_use_hawk == true
    - ansible_system == 'Linux'
