---

- name: Create /etc/pacemaker
  file: path=/etc/pacemaker state=directory owner=hacluster

- name: Disable and stop lvmetad
  service: name={{ item }} state=stopped enabled=no
  with_items:
   - lvm2-lvmetad.socket
   - lvm2-lvmetad.service

- name: Start apparmor
  service: name={{ item }} state=started enabled=yes
  with_items:
   - apparmor.service

# LXD does not need any monitoring script
- name: Monitoring script for LXC containers
  copy: src=monitor_lxc.sh dest=/opt/monitor_lxc.sh mode=0755
  when: ansible_os_family == 'Suse'

- name: Set SSL certs for Hawk
  copy: src={{ item }} dest=/etc/{{ item }} owner=root group=haclient mode=0640
  with_items:
    - "{{ cluster_hawk_file_key }}"
    - "{{ cluster_hawk_file_pem }}"
  notify: restart hawk
  when: cluster_use_hawk == true
