---

# The playbook is failed if misconfiguration
- include: options_check.yml
  run_once: true
  tags:
    - always
    - check

- include: packaging.yml
  tags:
    - packaging

- include: crmsh.yml
  tags:
    - cluster_cluster
    - cluster_packaging

- include: firewall.yml # TODO: ubuntu support
  when: ansible_os_family == 'Suse'
  tags:
    - cluster_firewall

- include: network.yml
  tags:
    - cluster_network

- include: configuration.yml
  tags:
    - cluster_configuration

- include: cgroups.yml
  when: ansible_os_family == 'Suse'
  tags:
    - cluster_cgroups

- include: cluster.yml
  tags:
    - cluster_cluster

- include: libvirt.yml
  when:
    - cluster_role == 'compute'
    - hosting_use_libvirt_lxc == true
  tags:
    - cluster_libvirt

- include: monitoring.yml
  tags:
   - cluster_monitoring

- include: metrics.yml
  tags:
    - cluster_metrics
