---

- include: metrics/suse.yml
  when: ansible_os_family == "SUSE"

- include: metrics/ubuntu.yml
  when: ansible_os_family == "Ubuntu"

- name: Configure telegraf
  template: src=telegraf/{{ item }}.j2 dest=/etc/telegraf/telegraf.d/{{ item }}
  with_items:
    - cluster.conf
  notify: restart telegraf
  when:
    - metrics_use_telegraf == true
    - ansible_virtualization_role == 'host'
