---

- include: monitoring/suse.yml
  when: ansible_os_family == "SUSE"

- include: monitoring/ubuntu.yml
  when: ansible_os_family == "Ubuntu"

- name: Set monitoring probes (nrpe)
  template: src=cluster.cfg.j2 dest=/etc/nrpe.d/cluster.cfg
  notify: restart nrpe
  when: monitoring_use_nrpe == true

- name: Set monitoring probes (consul)
  template: src=consul/cluster.json.j2 dest=/etc/consul.d/cluster.json
  notify: reload consul
  when: monitoring_use_consul == true
