---

- fail: msg='Only one monitoring method should be used'
  when:
   - monitoring_use_consul == true
   - monitoring_use_nrpe == true

- fail: msg='Only one metrics method should be used'
  when:
   - metrics_use_collectd == true
   - metrics_use_telegraf_== true

- fail: msg="Two is the minimum number of nodes"
  when:
    - cluster_expected_nodes < 2

- fail: msg="On a two-nodes cluster, a remote ping address must be given"
  when:
    - cluster_ping_remote_addr == 'None'
    - cluster_expected_nodes < 3
