# Copyright (C) 2016 Mathieu Grzybek
#
# License: GNU General Public License (GPL)
---
- version: 2.2
  category: Cluster
  shortdesc: Initialize a cloned systemd service.
  longdesc: |
    A cloned systemd primitive is created.
    The location is based on the value of the cluster_group attribute.

  parameters:
   - name: service
     shortdesc: Systemd service name.
     longdesc: Name of the system service to manage.
     required: true
     type: string

   - name: size
     shortdesc: Number of clones to run.
     longdesc: This is the number of nodes that should own the cluster_group attribute.
     required: true
     type: integer

   - name: cluster_group
     shortdesc: cluster_group value.
     longdesc: Value of the attribute called cluster_group.
     required: true
     type: string

   - name: application
     shortdesc: Usage name of the service to run.
     longdesc: This is the name of the software that is run by the service.
     required: true
     type: string

  actions:
    - cib: |
        primitive {{application}}_{{service}} systemd:{{service}}
          op monitor interval="60" timeout="60"

    - cib: |
        clone c-{{application}}_{{service}} {{application}}_{{service}} meta clone-max={{size}}

    - cib: |
        location loc_{{application}}_{{service}} c-{{application}}_{{service}} rule -inf: 'cluster_group' ne "{{cluster-group}}"
