# Copyright (C) 2016 Mathieu Grzybek
#
# License: GNU General Public License (GPL)
---
- version: 2.2
  category: Cluster
  shortdesc: Initialisation RG multi-noeuds.
  longdesc: |
    On installe un groupe avec un VG.
    On fixe sa position sur le noeud avec une contrainte en fonction de
    l'attribut cluster-group.

  parameters:
   - name: id
     shortdesc: Nom du groupe.
     longdesc: Nom de l'application.
     required: true
     type: string

   - name: cluster-group
     shortdesc: Groupe.
     longdesc: Valeur de l'attribut cluster-group.
     required: true
     type: string

  actions:
    - cib: |
        primitive {{id}}_vg LVM
         params volgrpname={{id}} exclusive=true partial_activation=true
         op monitor timeout=30 interval=10
         op start timeout=30 interval=0
         op stop timeout=30 interval=0

    - cib: |
        group {{id}}_rg {{id}}_vg

    - cib: |
        location loc_{{id}} {{id}}_rg
         rule -inf: 'cluster_group' ne "{{cluster-group}}"
         rule -inf: ovsmonitor-bond-front ne 1
         rule -inf: ovsmonitor-bond-back ne 1

    - cib: |
        order order_clvm_{{id}}_rg Mandatory: c-clvm:start {{id}}_rg:start
