---

- name: Allow login from pts/0
  copy: src=securetty dest=/srv/cluster/{{ application.name }}/etc/securetty

- name: Set hostname
  shell: "echo {{ application.name }} > /srv/cluster/{{ application.name }}/etc/hostname"

- name: Set the DNS servers
  shell: cp /etc/resolv.conf /srv/cluster/{{ application.name }}/etc/resolv.conf

#- name: Create an empty default config file for network
#  file: path=/srv/cluster/{{ application.name }}/etc/sysconfig/network state=touch

- name: Create custom directories
  file: path=/srv/cluster/{{ application.name }}/{{ item }} state=directory owner=root
  with_items:
    - /opt/stig
    - /etc/ansible/facts.d
    - /etc/pacemaker

- name: Mise en place du fichier d'authentification inter-noeuds
  copy: src=/etc/pacemaker/authkey dest=/srv/cluster/{{ application.name }}/etc/pacemaker/authkey remote_src=true

- name: Mise en place des bandeaux
  copy: src={{ item.source }} dest=/etc/{{ item.cible }}
  with_items:
    - source: issue
      cible: issue
    - source: "{{ motd }}"
      cible: motd
