---

# TODO: tina
- name: Declaration des services socles
  template: src=suse-firewall.j2 dest=/srv/cluster/{{ application.name }}/etc/sysconfig/SuSEfirewall2.d/services/{{ item.name }}
  with_items:
    - name: pacemaker-remote
      ports:
        - number: 3121
          protocol: tcp

- name: Mise en place de la zone externe - interfaces
  lineinfile: dest=/srv/cluster/{{ application.name }}/etc/sysconfig/SuSEfirewall2 regexp='^FW_DEV_EXT=' line='FW_DEV_EXT="public save"'

- name: Mise en place de la zone interne - interfaces
  lineinfile: dest=/srv/cluster/{{ application.name }}/etc/sysconfig/SuSEfirewall2 regexp='^FW_DEV_INT=' line='FW_DEV_INT="admin"'

- name: Recherche de la configuration de la zone interne
  shell: egrep -e "^FW_CONFIGURATIONS_INT=" /srv/cluster/{{ application.name }}/etc/sysconfig/SuSEfirewall2
  register: fw_int

- name: Mise en place des services - zone interne
  lineinfile: dest=/srv/cluster/{{ application.name }}/etc/sysconfig/SuSEfirewall2 regexp='^FW_CONFIGURATIONS_INT=' line='FW_CONFIGURATIONS_INT="sshd omnivision"'
  when: fw_int.stdout.find("sshd") < 0

- name: Mise en place du firewall - zone interne
  lineinfile: dest=/srv/cluster/{{ application.name }}/etc/sysconfig/SuSEfirewall2 regexp='^FW_PROTECT_FROM_INT=' line='FW_PROTECT_FROM_INT="yes"'

- name: Lancement du firewall au demarrage
  file: src=/usr/lib/systemd/system/{{ item }} dest=/srv/cluster/{{ application.name }}/etc/systemd/system/multi-user.target.wants/{{ item }} state=link
  with_items:
    - SuSEfirewall2_init.service
    - SuSEfirewall2.service
