---

- name: Configure SLES repositories
  zypper_repository: name="{{ item.name }}" repo="{{ item.url }}" state=present
  with_items:
    - name: sle-server-product
      url: "{{ repo_sle_server_product }}"
    - name: sle-server-updates
      url: "{{ repo_sle_server_updates }}"
    - name: sle-ha-product
      url: "{{ repo_sle_ha_product }}"
    - name: sle-ha-updates
      url: "{{ repo_sle_ha_updates }}"
  when:
    - ansible_distribution == 'SLES'
    - repo_sle_server_product != 'None'
    - repo_sle_server_updates != 'None'
    - repo_sle_ha_product != 'None'
    - repo_sle_ha_updates != 'None'

- name: Install base packages (SLES)
  zypper: type=pattern name={{ item }} state=present
  with_items:
    - Minimal
    - base
  when:
    - ansible_distribution == 'SLES'

- name: Install base packages (OpenSUSE)
  zypper: type=pattern name={{ item }} state=present
  with_items:
    - minimal_base
  when:
    - ansible_distribution != 'SLES'

#- name: Upgrade if pacemaker is not running
#  zypper: name=* state=latest force=true
#  when: pcmk_status.stdout.find("inactive") > -1

- name: Install some useful packages
  zypper: name={{ item }} state=present
  with_items:
    - lsb-release

- name: Install logging packages
  zypper: name={{ item }} state=present
  with_items:
    - rsyslog-module-rabbitmq
  when: logging_use_amqp == true

- name: Installation des paquets standards
  zypper: name={{ item }} state=present
  with_items:
    - openvswitch
    - open-lldp
  when:
#    - ansible_virtualization_role == "host"
    - cluster_role == 'compute'
    - net_use_openvswitch == true

- name: Install NRPE
  zypper: name={{ item }} state=present disable_gpg_check=yes
  with_items:
    - nrpe
    - monitoring-plugins-procs
    - monitoring-plugins-zypper
  when:
    - monitoring_use_nrpe == true

- name: NRPE checks for physical nodes
  zypper: name={{ item }} state=present disable_gpg_check=yes
  with_items:
    - monitoring-plugins-ntp_time
    - monitoring-plugins-multipath
  when:
    - ansible_virtualization_role == 'host'
    - monitoring_use_nrpe == true

- name: Start OpenVSwitch
  service: name=openvswitch-switch.service state=started enabled=true
  when:
      - cluster_role == 'compute'
      - net_use_openvswitch == true

- name: Rafraichissement de la liste des paquets dans le cron.daily
  copy: src=zypper.cron dest=/etc/cron.daily/zypper owner=root group=root mode=0755
