---

#- name: Upgrade if pacemaker is not running
#  apt: name=* state=latest
#  when: pcmk_status.stdout.find("inactive") > -1

- name: Install some useful packages
  apt: name={{ item }} state=present
  with_items:
    - lsb-release

- name: Install logging packages
  apt: name={{ item }} state=present
  with_items:
    - rsyslog-module-rabbitmq
  when: logging_use_amqp == true

- name: Installation des paquets standards
  apt: name={{ item }} state=present
  with_items:
    - openvswitch-switch
    - lldpad
  when:
#    - ansible_virtualization_role == "host"
    - cluster_role == 'compute'
    - net_use_openvswitch == true

- name: Install NRPE
  apt: name={{ item }} state=present
  with_items:
    - nagios-nrpe-server
    - monitoring-plugins-basic
  when:
    - monitoring_use_nrpe == true

# The available package is very heavy
#    - nagios-plugins-contrib

- name: Set NRPE service configuration
  copy: src=systemd/nrpe.service dest=/etc/systemd/system/nrpe.service
  notify: reload systemd

- name: Start OpenVSwitch
  service: name=openvswitch-switch.service state=started enabled=true
  when:
#    - ansible_virtualization_role == "host"
    - cluster_role == 'compute'
    - net_use_openvswitch == true

- name: Rafraichissement de la liste des paquets dans le cron.daily
  copy: src=apt.cron dest=/etc/cron.daily/apt owner=root group=root mode=0755
