---

- name: Create the bridge
  shell: ovs-vsctl --may-exist add-br {{ item.bridge }}

- name: Create the bond
  shell: ovs-vsctl --may-exist add-bond {{ item.bridge }} {{ item.bond }} {{ item.ethernet_ports }} lacp=active
  when: item.ethernet_ports.find(",") > -1

- name: Create the port
  shell: ovs-vsctl --may-exist add-port {{ item.bridge }} {{ item.ethernet_ports }}
  when: item.ethernet_ports.find(",") < 0
