---

- name: Create lxd switch
  shell: lxc network list|grep -q {{ item.bridge }} || lxc network create {{ item.bridge }} ipv6.address=none ipv4.address=none ipv4.nat=false

- name: Configure ovs
  shell: lxc network set {{ item.bridge }} bridge.driver openvswitch

- name: Attach ovs bridge to profile
  shell: lxc profile show default|grep -q {{ item.bridge }} || lxc network attach-profile {{ item.bridge }} default {{ item.interface }}

- name: Rename the interface
  shell: lxc profile device set default {{ item.interface }} name {{ item.interface }}
