---

- name: Configuration lvm.conf for multipath SAN
  copy: src=lvm.conf dest=/etc/lvm/lvm.conf

- name: Disable and stop lvmetad
  service: name={{ item }} state=stopped enabled=no
  with_items:
   - lvm2-lvmetad.socket
   - lvm2-lvmetad.service
  when: ansible_system == 'Linux'

- name: Set clvm and dlm resources
  shell: crm script run cloned_clvm size={{ cluster_compute_nodes }}
  run_once: true

- name: Wait for clvmd's availability
  wait_for: path=/var/run/lvm/clvmd.sock state=present delay=5 timeout=30
  when: ansible_virtualization_role == 'compute'
