---

- name: Check cluster status
  shell: crm configure show || true
  register: crm_configure_show

- name: Disable sbd is the node's role is not compute
  service: name=sbd enabled=false state=stopped
  when: cluster_role != 'compute'

- name: LUNs initialisation for SBD if the resource does not exist
  shell: sbd -d {{ item }} create
  with_items:
    - "{{ cluster_stonith_sbd_lun_1 }}"
    - "{{ cluster_stonith_sbd_lun_2 }}"
    - "{{ cluster_stonith_sbd_lun_3 }}"
  when:
    - crm_configure_show.stdout.find("sbd") < 0
    - cluster_role == 'compute'
  run_once: true

- name: Configure /etc/sysconfig/sbd if the resource does not exist
  replace: dest=/etc/sysconfig/sbd regexp='^SBD_DEVICE=(.*?)$' replace='SBD_DEVICE="{{ cluster_stonith_sbd_lun_1 }};{{ cluster_stonith_sbd_lun_2 }};{{ cluster_stonith_sbd_lun_3 }}"'
  when:
    - crm_resources_stonith.stdout.find("sbd") < 0
    - ansible_virtualization_role == 'host'
    - ansible_os_family == 'Suse'
  notify: restart sbd resource

- name: Configure /etc/default/sbd if the resource does not exist
  replace: dest=/etc/default/sbd regexp='^SBD_DEVICE=(.*?)$' replace='SBD_DEVICE="{{ cluster_stonith_sbd_lun_1 }};{{ cluster_stonith_sbd_lun_2 }};{{ cluster_stonith_sbd_lun_3 }}"'
  when:
    - crm_resources_stonith.stdout.find("sbd") < 0
    - ansible_virtualization_role == 'host'
    - ansible_distribution == 'Ubuntu'
  notify: restart sbd resource

- name: sbd on boot on compute nodes
  service: name=sbd enabled=yes
  when: cluster_role == 'compute'

# TODO: prevent node from joining the cluster if fenced
